### ISSUE TITLE
Add a scheduled reporting service 

### ISSUE THREAD

**Issue by Hillrunner2008** [Maxm326/Prep-Project#1]
EJBs have support simple annotation configured timers. Using the javax.ejb.Schedule annotation in a stateless EJB, please implement a scheduled reporting service that logs the size of the returned list from https://github.com/Maxm326/Prep-Project/blob/master/src/main/java/com/stackleader/PrepDao.java#L19 every 5 minutes.

**Comment by Maxm326** [comment]
Successfully added stateless EJB to log scheduled reports.
